-- noinspection SqlResolve
CREATE OR REPLACE VIEW VESTA.V_PLATFORM_PATIENTS
AS
SELECT 
    id,
    first_name,
    last_name,
    timezone,
    created_at,
    updated_at,
    plan,
    external_id,
    agency,
    status,
    payer_id,
    reporting_start_date,
    phone_number,
    birth_date,
    language,
    address_1,
    address_2,
    city,
    state,
    zip_code,
    owner_id,
    languages,
    gender,
    gender_comment,
    risk_profile_completed,
    risk_profile_completed_at,
    social_assessment_completed_at,
    self_directing,
    residence_type,
    residence_type_other,
    living_arrangement,
    living_arrangement_other,
    care_team_info,
    last_pcp_visit,
    enabled,
    test,
    expected_weekly_health_reports,
    consent_by,
    consent_at,
    plan_id,
    strengths_barriers,
    np_owner_id,
    health_gorilla_id,
    rpm_kit_pack,
    rpm_kit_id,
    input_organization_id,
    channel_id,
    notes,
    virtual_visit_date,
    deceased_date,
    risk_level,
    risk_level_updated_by,
    risk_level_updated_at
FROM "PC_FIVETRAN_DB"."DASHPROD_PUBLIC"."PLATFORM_PATIENTS"
WHERE _FIVETRAN_DELETED=false
AND enabled=TRUE
AND test=false
and status<>'INVALID'
;